/*
 * Interface for gwget
 */

#include <Bonobo.idl>

module GNOME {

	module Gwget {

		/* URIs are just plain strings, but we use a typedef to make
		 * the interface definitions clearer.
		 */
		typedef string URI;
		typedef sequence<URI> URIList;

		interface Application : Bonobo::Unknown {
			string echo();
			oneway void openURLSList (in URIList urls);
			oneway void quit ();
		};


	};
};
